# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circuitd.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='circuitd.proto',
  package='circuitd',
  serialized_pb='\n\x0e\x63ircuitd.proto\x12\x08\x63ircuitd\"W\n\rCreateCircuit\x12\x11\n\tclient_id\x18\x01 \x02(\x04\x12\x13\n\x0bnext_hop_ip\x18\x02 \x02(\r\x12\x1e\n\x16next_hop_authenticator\x18\x03 \x02(\x04\"Q\n\x0e\x43ircuitCreated\x12(\n\x07request\x18\x01 \x02(\x0b\x32\x17.circuitd.CreateCircuit\x12\x15\n\rauthenticator\x18\x02 \x02(\x03')




_CREATECIRCUIT = _descriptor.Descriptor(
  name='CreateCircuit',
  full_name='circuitd.CreateCircuit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='circuitd.CreateCircuit.client_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_hop_ip', full_name='circuitd.CreateCircuit.next_hop_ip', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_hop_authenticator', full_name='circuitd.CreateCircuit.next_hop_authenticator', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=115,
)


_CIRCUITCREATED = _descriptor.Descriptor(
  name='CircuitCreated',
  full_name='circuitd.CircuitCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='circuitd.CircuitCreated.request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authenticator', full_name='circuitd.CircuitCreated.authenticator', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=198,
)

_CIRCUITCREATED.fields_by_name['request'].message_type = _CREATECIRCUIT
DESCRIPTOR.message_types_by_name['CreateCircuit'] = _CREATECIRCUIT
DESCRIPTOR.message_types_by_name['CircuitCreated'] = _CIRCUITCREATED

class CreateCircuit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATECIRCUIT

  # @@protoc_insertion_point(class_scope:circuitd.CreateCircuit)

class CircuitCreated(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CIRCUITCREATED

  # @@protoc_insertion_point(class_scope:circuitd.CircuitCreated)


# @@protoc_insertion_point(module_scope)
