/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   messages__create_circuit__init
                     (Messages__CreateCircuit         *message)
{
  static Messages__CreateCircuit init_value = MESSAGES__CREATE_CIRCUIT__INIT;
  *message = init_value;
}
size_t messages__create_circuit__get_packed_size
                     (const Messages__CreateCircuit *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__create_circuit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t messages__create_circuit__pack
                     (const Messages__CreateCircuit *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__create_circuit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t messages__create_circuit__pack_to_buffer
                     (const Messages__CreateCircuit *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__create_circuit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Messages__CreateCircuit *
       messages__create_circuit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Messages__CreateCircuit *)
     protobuf_c_message_unpack (&messages__create_circuit__descriptor,
                                allocator, len, data);
}
void   messages__create_circuit__free_unpacked
                     (Messages__CreateCircuit *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__create_circuit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   messages__circuit_created__init
                     (Messages__CircuitCreated         *message)
{
  static Messages__CircuitCreated init_value = MESSAGES__CIRCUIT_CREATED__INIT;
  *message = init_value;
}
size_t messages__circuit_created__get_packed_size
                     (const Messages__CircuitCreated *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__circuit_created__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t messages__circuit_created__pack
                     (const Messages__CircuitCreated *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__circuit_created__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t messages__circuit_created__pack_to_buffer
                     (const Messages__CircuitCreated *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__circuit_created__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Messages__CircuitCreated *
       messages__circuit_created__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Messages__CircuitCreated *)
     protobuf_c_message_unpack (&messages__circuit_created__descriptor,
                                allocator, len, data);
}
void   messages__circuit_created__free_unpacked
                     (Messages__CircuitCreated *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__circuit_created__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   messages__check_failover__init
                     (Messages__CheckFailover         *message)
{
  static Messages__CheckFailover init_value = MESSAGES__CHECK_FAILOVER__INIT;
  *message = init_value;
}
size_t messages__check_failover__get_packed_size
                     (const Messages__CheckFailover *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t messages__check_failover__pack
                     (const Messages__CheckFailover *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t messages__check_failover__pack_to_buffer
                     (const Messages__CheckFailover *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Messages__CheckFailover *
       messages__check_failover__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Messages__CheckFailover *)
     protobuf_c_message_unpack (&messages__check_failover__descriptor,
                                allocator, len, data);
}
void   messages__check_failover__free_unpacked
                     (Messages__CheckFailover *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   messages__check_failover_acknowledge__init
                     (Messages__CheckFailoverAcknowledge         *message)
{
  static Messages__CheckFailoverAcknowledge init_value = MESSAGES__CHECK_FAILOVER_ACKNOWLEDGE__INIT;
  *message = init_value;
}
size_t messages__check_failover_acknowledge__get_packed_size
                     (const Messages__CheckFailoverAcknowledge *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover_acknowledge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t messages__check_failover_acknowledge__pack
                     (const Messages__CheckFailoverAcknowledge *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover_acknowledge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t messages__check_failover_acknowledge__pack_to_buffer
                     (const Messages__CheckFailoverAcknowledge *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover_acknowledge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Messages__CheckFailoverAcknowledge *
       messages__check_failover_acknowledge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Messages__CheckFailoverAcknowledge *)
     protobuf_c_message_unpack (&messages__check_failover_acknowledge__descriptor,
                                allocator, len, data);
}
void   messages__check_failover_acknowledge__free_unpacked
                     (Messages__CheckFailoverAcknowledge *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__check_failover_acknowledge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   messages__failover_complete__init
                     (Messages__FailoverComplete         *message)
{
  static Messages__FailoverComplete init_value = MESSAGES__FAILOVER_COMPLETE__INIT;
  *message = init_value;
}
size_t messages__failover_complete__get_packed_size
                     (const Messages__FailoverComplete *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__failover_complete__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t messages__failover_complete__pack
                     (const Messages__FailoverComplete *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__failover_complete__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t messages__failover_complete__pack_to_buffer
                     (const Messages__FailoverComplete *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__failover_complete__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Messages__FailoverComplete *
       messages__failover_complete__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Messages__FailoverComplete *)
     protobuf_c_message_unpack (&messages__failover_complete__descriptor,
                                allocator, len, data);
}
void   messages__failover_complete__free_unpacked
                     (Messages__FailoverComplete *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &messages__failover_complete__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor messages__create_circuit__field_descriptors[3] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CreateCircuit, client_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_hop_ip",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Messages__CreateCircuit, n_next_hop_ip),
    PROTOBUF_C_OFFSETOF(Messages__CreateCircuit, next_hop_ip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_hop_authenticator",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Messages__CreateCircuit, has_next_hop_authenticator),
    PROTOBUF_C_OFFSETOF(Messages__CreateCircuit, next_hop_authenticator),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned messages__create_circuit__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  2,   /* field[2] = next_hop_authenticator */
  1,   /* field[1] = next_hop_ip */
};
static const ProtobufCIntRange messages__create_circuit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor messages__create_circuit__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "messages.CreateCircuit",
  "CreateCircuit",
  "Messages__CreateCircuit",
  "messages",
  sizeof(Messages__CreateCircuit),
  3,
  messages__create_circuit__field_descriptors,
  messages__create_circuit__field_indices_by_name,
  1,  messages__create_circuit__number_ranges,
  (ProtobufCMessageInit) messages__create_circuit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor messages__circuit_created__field_descriptors[3] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CircuitCreated, request),
    &messages__create_circuit__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authenticator",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CircuitCreated, authenticator),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Messages__CircuitCreated, n_ip),
    PROTOBUF_C_OFFSETOF(Messages__CircuitCreated, ip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned messages__circuit_created__field_indices_by_name[] = {
  1,   /* field[1] = authenticator */
  2,   /* field[2] = ip */
  0,   /* field[0] = request */
};
static const ProtobufCIntRange messages__circuit_created__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor messages__circuit_created__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "messages.CircuitCreated",
  "CircuitCreated",
  "Messages__CircuitCreated",
  "messages",
  sizeof(Messages__CircuitCreated),
  3,
  messages__circuit_created__field_descriptors,
  messages__circuit_created__field_indices_by_name,
  1,  messages__circuit_created__number_ranges,
  (ProtobufCMessageInit) messages__circuit_created__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor messages__check_failover__field_descriptors[2] =
{
  {
    "authenticator",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CheckFailover, authenticator),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "should_forward",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CheckFailover, should_forward),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned messages__check_failover__field_indices_by_name[] = {
  0,   /* field[0] = authenticator */
  1,   /* field[1] = should_forward */
};
static const ProtobufCIntRange messages__check_failover__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor messages__check_failover__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "messages.CheckFailover",
  "CheckFailover",
  "Messages__CheckFailover",
  "messages",
  sizeof(Messages__CheckFailover),
  2,
  messages__check_failover__field_descriptors,
  messages__check_failover__field_indices_by_name,
  1,  messages__check_failover__number_ranges,
  (ProtobufCMessageInit) messages__check_failover__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor messages__check_failover_acknowledge__field_descriptors[1] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__CheckFailoverAcknowledge, request),
    &messages__check_failover__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned messages__check_failover_acknowledge__field_indices_by_name[] = {
  0,   /* field[0] = request */
};
static const ProtobufCIntRange messages__check_failover_acknowledge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor messages__check_failover_acknowledge__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "messages.CheckFailoverAcknowledge",
  "CheckFailoverAcknowledge",
  "Messages__CheckFailoverAcknowledge",
  "messages",
  sizeof(Messages__CheckFailoverAcknowledge),
  1,
  messages__check_failover_acknowledge__field_descriptors,
  messages__check_failover_acknowledge__field_indices_by_name,
  1,  messages__check_failover_acknowledge__number_ranges,
  (ProtobufCMessageInit) messages__check_failover_acknowledge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor messages__failover_complete__field_descriptors[2] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__FailoverComplete, success),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Messages__FailoverComplete, request),
    &messages__check_failover__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned messages__failover_complete__field_indices_by_name[] = {
  1,   /* field[1] = request */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange messages__failover_complete__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor messages__failover_complete__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "messages.FailoverComplete",
  "FailoverComplete",
  "Messages__FailoverComplete",
  "messages",
  sizeof(Messages__FailoverComplete),
  2,
  messages__failover_complete__field_descriptors,
  messages__failover_complete__field_indices_by_name,
  1,  messages__failover_complete__number_ranges,
  (ProtobufCMessageInit) messages__failover_complete__init,
  NULL,NULL,NULL    /* reserved[123] */
};
