# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='messages',
  serialized_pb='\n\x0emessages.proto\x12\x08messages\"W\n\rCreateCircuit\x12\x11\n\tclient_id\x18\x01 \x02(\x04\x12\x13\n\x0bnext_hop_ip\x18\x02 \x03(\t\x12\x1e\n\x16next_hop_authenticator\x18\x03 \x01(\x04\"]\n\x0e\x43ircuitCreated\x12(\n\x07request\x18\x01 \x02(\x0b\x32\x17.messages.CreateCircuit\x12\x15\n\rauthenticator\x18\x02 \x02(\x03\x12\n\n\x02ip\x18\x03 \x03(\t\">\n\rCheckFailover\x12\x15\n\rauthenticator\x18\x01 \x02(\x04\x12\x16\n\x0eshould_forward\x18\x02 \x02(\x08\"D\n\x18\x43heckFailoverAcknowledge\x12(\n\x07request\x18\x01 \x02(\x0b\x32\x17.messages.CheckFailover\"M\n\x10\x46\x61iloverComplete\x12(\n\x07request\x18\x02 \x02(\x0b\x32\x17.messages.CheckFailover\x12\x0f\n\x07success\x18\x01 \x02(\x08')




_CREATECIRCUIT = _descriptor.Descriptor(
  name='CreateCircuit',
  full_name='messages.CreateCircuit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='messages.CreateCircuit.client_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_hop_ip', full_name='messages.CreateCircuit.next_hop_ip', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_hop_authenticator', full_name='messages.CreateCircuit.next_hop_authenticator', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=115,
)


_CIRCUITCREATED = _descriptor.Descriptor(
  name='CircuitCreated',
  full_name='messages.CircuitCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='messages.CircuitCreated.request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authenticator', full_name='messages.CircuitCreated.authenticator', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='messages.CircuitCreated.ip', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=210,
)


_CHECKFAILOVER = _descriptor.Descriptor(
  name='CheckFailover',
  full_name='messages.CheckFailover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authenticator', full_name='messages.CheckFailover.authenticator', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='should_forward', full_name='messages.CheckFailover.should_forward', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=274,
)


_CHECKFAILOVERACKNOWLEDGE = _descriptor.Descriptor(
  name='CheckFailoverAcknowledge',
  full_name='messages.CheckFailoverAcknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='messages.CheckFailoverAcknowledge.request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=276,
  serialized_end=344,
)


_FAILOVERCOMPLETE = _descriptor.Descriptor(
  name='FailoverComplete',
  full_name='messages.FailoverComplete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='messages.FailoverComplete.request', index=0,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='messages.FailoverComplete.success', index=1,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=346,
  serialized_end=423,
)

_CIRCUITCREATED.fields_by_name['request'].message_type = _CREATECIRCUIT
_CHECKFAILOVERACKNOWLEDGE.fields_by_name['request'].message_type = _CHECKFAILOVER
_FAILOVERCOMPLETE.fields_by_name['request'].message_type = _CHECKFAILOVER
DESCRIPTOR.message_types_by_name['CreateCircuit'] = _CREATECIRCUIT
DESCRIPTOR.message_types_by_name['CircuitCreated'] = _CIRCUITCREATED
DESCRIPTOR.message_types_by_name['CheckFailover'] = _CHECKFAILOVER
DESCRIPTOR.message_types_by_name['CheckFailoverAcknowledge'] = _CHECKFAILOVERACKNOWLEDGE
DESCRIPTOR.message_types_by_name['FailoverComplete'] = _FAILOVERCOMPLETE

class CreateCircuit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATECIRCUIT

  # @@protoc_insertion_point(class_scope:messages.CreateCircuit)

class CircuitCreated(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CIRCUITCREATED

  # @@protoc_insertion_point(class_scope:messages.CircuitCreated)

class CheckFailover(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKFAILOVER

  # @@protoc_insertion_point(class_scope:messages.CheckFailover)

class CheckFailoverAcknowledge(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKFAILOVERACKNOWLEDGE

  # @@protoc_insertion_point(class_scope:messages.CheckFailoverAcknowledge)

class FailoverComplete(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAILOVERCOMPLETE

  # @@protoc_insertion_point(class_scope:messages.FailoverComplete)


# @@protoc_insertion_point(module_scope)
